title: Chencen Liang's Homepage
page-top-title: Chencen Liang
top-section-bg-text: Urban and Rural Planning
home-subtitle: Chencen Liang&ensp;|&ensp;梁陈岑
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
